### ISSUE TITLE
Search function does not produce results

### ISSUE THREAD

**Issue by buerki** [troyeguo/koodo-reader#88]
When I use the search field, no results appear even if there should be results:
1. I search for part of a title of a book (or author surname)
2. no books appear (in the example below I would expect 'Cognitive Lexicography' to appear)
3. I press cancel
4. all book reappear

MacOS 11.2.2
Koodo Version 1.2.2 (1.2.2.296)

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1183611/109477755-54a5a600-7a70-11eb-9b58-8e7bdccd686a.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1183611/109477812-65eeb280-7a70-11eb-8fed-05c740f773a9.png">

Many thanks!

**Comment by troyeguo** [comment]
Thanks for your feedback, this bug happens because koodo reader will convert all the books name and author name into lower case, and compare the text you input with these names. if you search the word "cognitive" not "Cognitive", this book will show up. We will resolve this issue in the next version.

**Comment by buerki** [comment]
Excellent, many thanks! I can confirm it works fine if I use lowercase.
